const fs = require("fs");
const path = require("path");
const { v4: uuidv4 } = require("uuid");

const DB_PATH = path.join(__dirname, "crm-data.json");

const now = () => new Date().toISOString();
const daysAgo = (d) => new Date(Date.now() - 86400000 * d).toISOString();

const defaultData = {
  leads: [
    {
      id: uuidv4(),
      title: "Accounting Software Lead - TechCorp",
      name: "Rajesh Kumar",
      phone: "+1-555-0101",
      email: "rajesh@techcorp.com",
      amount: 5000,
      currency: "USD",
      stage: "Fresh Leads",
      source: "Website",
      responsible: "Govind Kaushik",
      company: "TechCorp Solutions",
      notes: "Interested in bookkeeping services",
      priority: "high",
      status: "active",
      created_at: daysAgo(10),
    },
    {
      id: uuidv4(),
      title: "Outsourced Bookkeeping - Sandeep Sharma",
      name: "Sandeep Sharma",
      phone: "+1-555-0102",
      email: "sandeep@company.com",
      amount: 3500,
      currency: "USD",
      stage: "Assigned Leads",
      source: "Referral",
      responsible: "Govind Kaushik",
      company: "Sharma Enterprises",
      notes: "Referred by existing client",
      priority: "medium",
      status: "active",
      created_at: daysAgo(8),
    },
    {
      id: uuidv4(),
      title: "Tax Filing Services - Divya Verma",
      name: "Divya Verma",
      phone: "+1-555-0103",
      email: "divya@business.com",
      amount: 2000,
      currency: "USD",
      stage: "Connected / In Progress",
      source: "Cold Call",
      responsible: "Govind Kaushik",
      company: "Verma & Associates",
      notes: "Annual tax filing + monthly bookkeeping",
      priority: "medium",
      status: "active",
      created_at: daysAgo(6),
    },
    {
      id: uuidv4(),
      title: "Monthly Accounting - Priya Singh",
      name: "Priya Singh",
      phone: "+1-555-0104",
      email: "priya@singh.com",
      amount: 1800,
      currency: "USD",
      stage: "No Answer",
      source: "Facebook",
      responsible: "Govind Kaushik",
      company: "Singh LLC",
      notes: "Called 3 times, no answer",
      priority: "low",
      status: "active",
      created_at: daysAgo(5),
    },
    {
      id: uuidv4(),
      title: "Payroll Services - Empire Insulation",
      name: "Mike Johnson",
      phone: "+1-555-0105",
      email: "mike@empireinsulation.com",
      amount: 4500,
      currency: "USD",
      stage: "Need to connect in future",
      source: "Partner",
      responsible: "Govind Kaushik",
      company: "Empire Insulation",
      notes: "Follow up in Q2 2026",
      priority: "high",
      status: "active",
      created_at: daysAgo(4),
    },
    {
      id: uuidv4(),
      title: "QuickBooks Setup - Small Biz",
      name: "Sarah Chen",
      phone: "+1-555-0106",
      email: "sarah@smallbiz.com",
      amount: 1200,
      currency: "USD",
      stage: "Fresh Leads",
      source: "Instagram",
      responsible: "Govind Kaushik",
      company: "Chen's Bakery",
      notes: "Needs QuickBooks setup and training",
      priority: "low",
      status: "active",
      created_at: daysAgo(3),
    },
    {
      id: uuidv4(),
      title: "CFO Services - Healthcare Clinic",
      name: "Dr. Anil Gupta",
      phone: "+1-555-0107",
      email: "agupta@clinic.com",
      amount: 8000,
      currency: "USD",
      stage: "Assigned Leads",
      source: "Website",
      responsible: "Govind Kaushik",
      company: "Gupta Medical Clinic",
      notes: "Fractional CFO services needed",
      priority: "high",
      status: "active",
      created_at: daysAgo(2),
    },
    {
      id: uuidv4(),
      title: "Accounts Payable - Hernandez Tax",
      name: "Carlos Hernandez",
      phone: "+1-555-0108",
      email: "carlos@hernandez.tax",
      amount: 3000,
      currency: "USD",
      stage: "Connected / In Progress",
      source: "Referral",
      responsible: "Govind Kaushik",
      company: "Hernandez Tax Services",
      notes: "Competitor referral - switch from Intuit",
      priority: "medium",
      status: "active",
      created_at: daysAgo(1),
    },
    {
      id: uuidv4(),
      title: "E-commerce Bookkeeping - ShopRight",
      name: "Lisa Wang",
      phone: "+1-555-0109",
      email: "lisa@shopright.com",
      amount: 2800,
      currency: "USD",
      stage: "Fresh Leads",
      source: "Email",
      responsible: "Govind Kaushik",
      company: "ShopRight Inc.",
      notes: "High-volume Shopify store needs reconciliation",
      priority: "medium",
      status: "active",
      created_at: now(),
    },
    {
      id: uuidv4(),
      title: "Non-Profit Accounting - Community Org",
      name: "Pastor Williams",
      phone: "+1-555-0110",
      email: "pastor@community.org",
      amount: 1500,
      currency: "USD",
      stage: "No Answer",
      source: "Cold Call",
      responsible: "Govind Kaushik",
      company: "Community First Church",
      notes: "Non-profit with 3 employees",
      priority: "low",
      status: "active",
      created_at: now(),
    },
    {
      id: uuidv4(),
      title: "Payroll Management - Azure Tech",
      name: "David Miller",
      phone: "+1-555-0111",
      email: "david@azuretech.com",
      amount: 6200,
      currency: "USD",
      stage: "Fresh Leads",
      source: "Website",
      responsible: "Govind Kaushik",
      company: "Azure Tech LLC",
      notes: "50 employees payroll",
      priority: "high",
      status: "active",
      created_at: daysAgo(12),
    },
    {
      id: uuidv4(),
      title: "Annual Audit - Western Holdings",
      name: "Robert Brown",
      phone: "+1-555-0112",
      email: "r.brown@western.com",
      amount: 9500,
      currency: "USD",
      stage: "Assigned Leads",
      source: "Partner",
      responsible: "Govind Kaushik",
      company: "Western Holdings",
      notes: "Annual audit required by board",
      priority: "high",
      status: "active",
      created_at: daysAgo(15),
    },
  ],
  deals: [
    {
      id: uuidv4(),
      title: "Monthly Bookkeeping Package - TechCorp",
      contact_name: "Rajesh Kumar",
      company_name: "TechCorp Solutions",
      phone: "+1-555-0101",
      email: "rajesh@techcorp.com",
      amount: 5000,
      currency: "USD",
      stage: "New Opportunity",
      source: "Website",
      responsible: "Govind Kaushik",
      notes: "Full-service monthly bookkeeping",
      close_date: "2026-05-30",
      probability: 30,
      priority: "high",
      status: "active",
      created_at: daysAgo(9),
    },
    {
      id: uuidv4(),
      title: "Annual Tax Filing - Sharma Enterprises",
      contact_name: "Sandeep Sharma",
      company_name: "Sharma Enterprises",
      phone: "+1-555-0102",
      email: "sandeep@company.com",
      amount: 3500,
      currency: "USD",
      stage: "In Progress",
      source: "Referral",
      responsible: "Govind Kaushik",
      notes: "Proposal sent, awaiting approval",
      close_date: "2026-04-15",
      probability: 60,
      priority: "medium",
      status: "active",
      created_at: daysAgo(7),
    },
    {
      id: uuidv4(),
      title: "Fractional CFO Services - Gupta Clinic",
      contact_name: "Dr. Anil Gupta",
      company_name: "Gupta Medical Clinic",
      phone: "+1-555-0107",
      email: "agupta@clinic.com",
      amount: 8000,
      currency: "USD",
      stage: "Agreement",
      source: "Website",
      responsible: "Govind Kaushik",
      notes: "Contract under review by their lawyer",
      close_date: "2026-04-30",
      probability: 85,
      priority: "high",
      status: "active",
      created_at: daysAgo(5),
    },
    {
      id: uuidv4(),
      title: "Payroll + Bookkeeping Bundle",
      contact_name: "Mike Johnson",
      company_name: "Empire Insulation",
      phone: "+1-555-0105",
      email: "mike@empireinsulation.com",
      amount: 4500,
      currency: "USD",
      stage: "Won",
      source: "Partner",
      responsible: "Govind Kaushik",
      notes: "Signed! Starting May 1",
      close_date: "2026-04-01",
      probability: 100,
      priority: "high",
      status: "active",
      created_at: daysAgo(14),
    },
    {
      id: uuidv4(),
      title: "QuickBooks Migration - Chen's Bakery",
      contact_name: "Sarah Chen",
      company_name: "Chen's Bakery",
      phone: "+1-555-0106",
      email: "sarah@smallbiz.com",
      amount: 1200,
      currency: "USD",
      stage: "New Opportunity",
      source: "Instagram",
      responsible: "Govind Kaushik",
      notes: "Needs data migration from Wave",
      close_date: "2026-06-15",
      probability: 20,
      priority: "low",
      status: "active",
      created_at: daysAgo(2),
    },
    {
      id: uuidv4(),
      title: "E-commerce Reconciliation - ShopRight",
      contact_name: "Lisa Wang",
      company_name: "ShopRight Inc.",
      phone: "+1-555-0109",
      email: "lisa@shopright.com",
      amount: 2800,
      currency: "USD",
      stage: "In Progress",
      source: "Email",
      responsible: "Govind Kaushik",
      notes: "Demo scheduled for April 20",
      close_date: "2026-05-01",
      probability: 50,
      priority: "medium",
      status: "active",
      created_at: daysAgo(1),
    },
    {
      id: uuidv4(),
      title: "AP/AR Services - Hernandez Tax",
      contact_name: "Carlos Hernandez",
      company_name: "Hernandez Tax Services",
      phone: "+1-555-0108",
      email: "carlos@hernandez.tax",
      amount: 3000,
      currency: "USD",
      stage: "Lost",
      source: "Referral",
      responsible: "Govind Kaushik",
      notes: "Went with competitor",
      close_date: "2026-03-15",
      probability: 0,
      priority: "medium",
      status: "inactive",
      created_at: daysAgo(20),
    },
    {
      id: uuidv4(),
      title: "Annual Audit Package - Western Holdings",
      contact_name: "Robert Brown",
      company_name: "Western Holdings",
      phone: "+1-555-0112",
      email: "r.brown@western.com",
      amount: 9500,
      currency: "USD",
      stage: "Agreement",
      source: "Partner",
      responsible: "Govind Kaushik",
      notes: "Pending signature",
      close_date: "2026-04-25",
      probability: 80,
      priority: "high",
      status: "active",
      created_at: daysAgo(3),
    },
    {
      id: uuidv4(),
      title: "Payroll Management - Azure Tech",
      contact_name: "David Miller",
      company_name: "Azure Tech LLC",
      phone: "+1-555-0111",
      email: "david@azuretech.com",
      amount: 6200,
      currency: "USD",
      stage: "Won",
      source: "Website",
      responsible: "Govind Kaushik",
      notes: "Contract signed March 2026",
      close_date: "2026-03-20",
      probability: 100,
      priority: "high",
      status: "active",
      created_at: daysAgo(25),
    },
  ],
  contacts: [
    {
      id: uuidv4(),
      name: "Rajesh Kumar",
      first_name: "Rajesh",
      last_name: "Kumar",
      phone: "+1-555-0101",
      email: "rajesh@techcorp.com",
      type: "Clients-Bill To",
      company: "TechCorp Solutions",
      position: "CFO",
      source: "Website",
      responsible: "Govind Kaushik",
      country: "USA",
      present_software: "Excel",
      notes: "",
      created_at: daysAgo(30),
    },
    {
      id: uuidv4(),
      name: "Sandeep Sharma",
      first_name: "Sandeep",
      last_name: "Sharma",
      phone: "+1-555-0102",
      email: "sandeep@company.com",
      type: "Clients-Bill To",
      company: "Sharma Enterprises",
      position: "Owner",
      source: "Referral",
      responsible: "Govind Kaushik",
      country: "USA",
      present_software: "QuickBooks",
      notes: "",
      created_at: daysAgo(25),
    },
    {
      id: uuidv4(),
      name: "Divya Verma",
      first_name: "Divya",
      last_name: "Verma",
      phone: "+1-555-0103",
      email: "divya@business.com",
      type: "Job Seekers",
      company: "Verma & Associates",
      position: "Manager",
      source: "Cold Call",
      responsible: "Govind Kaushik",
      country: "Canada",
      present_software: "FreshBooks",
      notes: "",
      created_at: daysAgo(20),
    },
    {
      id: uuidv4(),
      name: "Mike Johnson",
      first_name: "Mike",
      last_name: "Johnson",
      phone: "+1-555-0105",
      email: "mike@empireinsulation.com",
      type: "Clients-Bill To",
      company: "Empire Insulation",
      position: "CEO",
      source: "Partner",
      responsible: "Govind Kaushik",
      country: "USA",
      present_software: "None",
      notes: "",
      created_at: daysAgo(15),
    },
    {
      id: uuidv4(),
      name: "Dr. Anil Gupta",
      first_name: "Anil",
      last_name: "Gupta",
      phone: "+1-555-0107",
      email: "agupta@clinic.com",
      type: "Clients-Bill To",
      company: "Gupta Medical Clinic",
      position: "Director",
      source: "Website",
      responsible: "Govind Kaushik",
      country: "USA",
      present_software: "Sage",
      notes: "",
      created_at: daysAgo(10),
    },
    {
      id: uuidv4(),
      name: "Amit Kumar",
      first_name: "Amit",
      last_name: "Kumar",
      phone: "+91-98765-43210",
      email: "amit@outsourced.com",
      type: "HR",
      company: "Outsourced Bookkeeping",
      position: "Senior Accountant",
      source: "Website",
      responsible: "Govind Kaushik",
      country: "India",
      present_software: "Tally",
      notes: "Internal staff",
      created_at: daysAgo(60),
    },
    {
      id: uuidv4(),
      name: "Lisa Wang",
      first_name: "Lisa",
      last_name: "Wang",
      phone: "+1-555-0109",
      email: "lisa@shopright.com",
      type: "Job Seekers",
      company: "ShopRight Inc.",
      position: "Operations Manager",
      source: "Email",
      responsible: "Govind Kaushik",
      country: "USA",
      present_software: "Wave",
      notes: "",
      created_at: daysAgo(5),
    },
    {
      id: uuidv4(),
      name: "Carlos Hernandez",
      first_name: "Carlos",
      last_name: "Hernandez",
      phone: "+1-555-0108",
      email: "carlos@hernandez.tax",
      type: "Other",
      company: "Hernandez Tax Services",
      position: "Tax Attorney",
      source: "Referral",
      responsible: "Govind Kaushik",
      country: "USA",
      present_software: "Intuit Pro",
      notes: "",
      created_at: daysAgo(25),
    },
    {
      id: uuidv4(),
      name: "Sarah Chen",
      first_name: "Sarah",
      last_name: "Chen",
      phone: "+1-555-0106",
      email: "sarah@smallbiz.com",
      type: "Job Seekers",
      company: "Chen's Bakery",
      position: "Owner",
      source: "Instagram",
      responsible: "Govind Kaushik",
      country: "USA",
      present_software: "Excel",
      notes: "",
      created_at: daysAgo(3),
    },
    {
      id: uuidv4(),
      name: "Robert Brown",
      first_name: "Robert",
      last_name: "Brown",
      phone: "+1-555-0112",
      email: "r.brown@western.com",
      type: "Clients-Bill To",
      company: "Western Holdings",
      position: "Finance Director",
      source: "Partner",
      responsible: "Govind Kaushik",
      country: "USA",
      present_software: "SAP",
      notes: "",
      created_at: daysAgo(15),
    },
    {
      id: uuidv4(),
      name: "David Miller",
      first_name: "David",
      last_name: "Miller",
      phone: "+1-555-0111",
      email: "david@azuretech.com",
      type: "Clients-Bill To",
      company: "Azure Tech LLC",
      position: "COO",
      source: "Website",
      responsible: "Govind Kaushik",
      country: "USA",
      present_software: "NetSuite",
      notes: "",
      created_at: daysAgo(12),
    },
    {
      id: uuidv4(),
      name: "Govind Kaushik",
      first_name: "Govind",
      last_name: "Kaushik",
      phone: "+91-98765-00001",
      email: "govind@outsourced.com",
      type: "HR",
      company: "Outsourced Bookkeeping",
      position: "Managing Partner",
      source: "Website",
      responsible: "Admin",
      country: "India",
      present_software: "QuickBooks Online",
      notes: "Primary responsible",
      created_at: daysAgo(365),
    },
  ],
  companies: [
    {
      id: uuidv4(),
      name: "TechCorp Solutions",
      phone: "+1-555-0101",
      email: "info@techcorp.com",
      website: "techcorp.com",
      industry: "Technology",
      employees: 45,
      revenue: 5000000,
      address: "123 Tech Ave",
      city: "San Francisco",
      country: "USA",
      responsible: "Govind Kaushik",
      source: "Website",
      notes: "",
      created_at: daysAgo(30),
    },
    {
      id: uuidv4(),
      name: "Empire Insulation",
      phone: "+1-555-0105",
      email: "info@empireinsulation.com",
      website: "empireinsulation.com",
      industry: "Manufacturing",
      employees: 120,
      revenue: 8000000,
      address: "456 Industrial Blvd",
      city: "Chicago",
      country: "USA",
      responsible: "Govind Kaushik",
      source: "Partner",
      notes: "",
      created_at: daysAgo(20),
    },
    {
      id: uuidv4(),
      name: "Hernandez Tax Services",
      phone: "+1-555-0108",
      email: "info@hernandez.tax",
      website: "hernandez.tax",
      industry: "Legal",
      employees: 12,
      revenue: 1500000,
      address: "789 Tax Court",
      city: "Miami",
      country: "USA",
      responsible: "Govind Kaushik",
      source: "Referral",
      notes: "",
      created_at: daysAgo(25),
    },
    {
      id: uuidv4(),
      name: "Gupta Medical Clinic",
      phone: "+1-555-0107",
      email: "admin@guptaclinic.com",
      website: "guptaclinic.com",
      industry: "Healthcare",
      employees: 30,
      revenue: 4200000,
      address: "321 Health Way",
      city: "New York",
      country: "USA",
      responsible: "Govind Kaushik",
      source: "Website",
      notes: "",
      created_at: daysAgo(10),
    },
    {
      id: uuidv4(),
      name: "Outsourced Bookkeeping",
      phone: "+91-98765-43210",
      email: "sales@backofficeaccountants.com",
      website: "outsourcedbookeeping.org",
      industry: "Accounting",
      employees: 25,
      revenue: 2000000,
      address: "Sector 17",
      city: "Chandigarh",
      country: "India",
      responsible: "Admin",
      source: "Direct",
      notes: "Our own company",
      created_at: daysAgo(365),
    },
    {
      id: uuidv4(),
      name: "ShopRight Inc.",
      phone: "+1-555-0109",
      email: "ops@shopright.com",
      website: "shopright.com",
      industry: "Retail",
      employees: 8,
      revenue: 900000,
      address: "55 Commerce St",
      city: "Austin",
      country: "USA",
      responsible: "Govind Kaushik",
      source: "Email",
      notes: "",
      created_at: daysAgo(2),
    },
    {
      id: uuidv4(),
      name: "Western Holdings",
      phone: "+1-555-0112",
      email: "info@western.com",
      website: "westernholdings.com",
      industry: "Finance",
      employees: 200,
      revenue: 50000000,
      address: "1 Finance Plaza",
      city: "Dallas",
      country: "USA",
      responsible: "Govind Kaushik",
      source: "Partner",
      notes: "",
      created_at: daysAgo(15),
    },
    {
      id: uuidv4(),
      name: "Azure Tech LLC",
      phone: "+1-555-0111",
      email: "ops@azuretech.com",
      website: "azuretech.com",
      industry: "Technology",
      employees: 50,
      revenue: 12000000,
      address: "200 Innovation Dr",
      city: "Seattle",
      country: "USA",
      responsible: "Govind Kaushik",
      source: "Website",
      notes: "",
      created_at: daysAgo(12),
    },
  ],
  activities: [
    {
      id: uuidv4(),
      type: "call",
      title: "Follow-up call with Rajesh Kumar",
      description: "Discuss bookkeeping package pricing",
      entity_type: "lead",
      entity_id: "",
      assigned_to: "Govind Kaushik",
      due_date: "2026-04-15",
      due_time: "10:00",
      completed: false,
      direction: "outgoing",
      duration: 30,
      created_at: daysAgo(2),
    },
    {
      id: uuidv4(),
      type: "email",
      title: "Send proposal to Sandeep Sharma",
      description: "Attach full proposal PDF",
      entity_type: "deal",
      entity_id: "",
      assigned_to: "Govind Kaushik",
      due_date: "2026-04-14",
      due_time: "14:00",
      completed: true,
      direction: "outgoing",
      duration: null,
      created_at: daysAgo(3),
    },
    {
      id: uuidv4(),
      type: "meeting",
      title: "CFO Services presentation - Gupta Clinic",
      description: "Online demo via Zoom",
      entity_type: "deal",
      entity_id: "",
      assigned_to: "Govind Kaushik",
      due_date: "2026-04-16",
      due_time: "11:00",
      completed: false,
      direction: "outgoing",
      duration: 60,
      created_at: daysAgo(1),
    },
    {
      id: uuidv4(),
      type: "task",
      title: "Prepare tax documents for Sharma Enterprises",
      description: "Gather Q1 2026 statements",
      entity_type: "deal",
      entity_id: "",
      assigned_to: "Amit Kumar",
      due_date: "2026-04-18",
      due_time: "09:00",
      completed: false,
      direction: "incoming",
      duration: null,
      created_at: daysAgo(1),
    },
    {
      id: uuidv4(),
      type: "call",
      title: "Welcome call - Empire Insulation",
      description: "Onboarding call for new client",
      entity_type: "deal",
      entity_id: "",
      assigned_to: "Govind Kaushik",
      due_date: "2026-04-20",
      due_time: "15:00",
      completed: false,
      direction: "outgoing",
      duration: 45,
      created_at: now(),
    },
    {
      id: uuidv4(),
      type: "email",
      title: "Invoice sent to Azure Tech LLC",
      description: "Monthly bookkeeping invoice #INV-2026-003",
      entity_type: "deal",
      entity_id: "",
      assigned_to: "Govind Kaushik",
      due_date: "2026-04-13",
      due_time: "09:00",
      completed: true,
      direction: "outgoing",
      duration: null,
      created_at: daysAgo(1),
    },
  ],
  comments: [],
  products: [
    {
      id: uuidv4(),
      name: "Monthly Bookkeeping - Small Business",
      description: "Full-service monthly bookkeeping for businesses up to 50 transactions/month",
      category: "Bookkeeping",
      price: 299,
      currency: "USD",
      tax_rate: 0,
      unit: "month",
      sku: "BK-SB-001",
      active: true,
      created_at: daysAgo(90),
    },
    {
      id: uuidv4(),
      name: "Monthly Bookkeeping - Medium Business",
      description: "Full-service monthly bookkeeping for businesses up to 200 transactions/month",
      category: "Bookkeeping",
      price: 599,
      currency: "USD",
      tax_rate: 0,
      unit: "month",
      sku: "BK-MB-002",
      active: true,
      created_at: daysAgo(90),
    },
    {
      id: uuidv4(),
      name: "Monthly Bookkeeping - Enterprise",
      description: "Full-service monthly bookkeeping for businesses with unlimited transactions",
      category: "Bookkeeping",
      price: 999,
      currency: "USD",
      tax_rate: 0,
      unit: "month",
      sku: "BK-ENT-003",
      active: true,
      created_at: daysAgo(90),
    },
    {
      id: uuidv4(),
      name: "Annual Tax Filing - Individual",
      description: "Complete personal tax return preparation and filing",
      category: "Tax",
      price: 350,
      currency: "USD",
      tax_rate: 0,
      unit: "year",
      sku: "TAX-IND-001",
      active: true,
      created_at: daysAgo(90),
    },
    {
      id: uuidv4(),
      name: "Annual Tax Filing - Business (S-Corp)",
      description: "S-Corp business tax return preparation and filing",
      category: "Tax",
      price: 850,
      currency: "USD",
      tax_rate: 0,
      unit: "year",
      sku: "TAX-SCORP-002",
      active: true,
      created_at: daysAgo(90),
    },
    {
      id: uuidv4(),
      name: "Annual Tax Filing - Business (C-Corp)",
      description: "C-Corp business tax return preparation and filing",
      category: "Tax",
      price: 1200,
      currency: "USD",
      tax_rate: 0,
      unit: "year",
      sku: "TAX-CCORP-003",
      active: true,
      created_at: daysAgo(90),
    },
    {
      id: uuidv4(),
      name: "Fractional CFO Services",
      description:
        "Part-time CFO services including financial strategy, reporting, and investor relations",
      category: "CFO Services",
      price: 2500,
      currency: "USD",
      tax_rate: 0,
      unit: "month",
      sku: "CFO-FRAC-001",
      active: true,
      created_at: daysAgo(60),
    },
    {
      id: uuidv4(),
      name: "Payroll Processing - Up to 10 employees",
      description: "Full payroll management including tax filings and direct deposit",
      category: "Payroll",
      price: 199,
      currency: "USD",
      tax_rate: 0,
      unit: "month",
      sku: "PAY-SM-001",
      active: true,
      created_at: daysAgo(60),
    },
    {
      id: uuidv4(),
      name: "Payroll Processing - 11-50 employees",
      description: "Full payroll management for mid-size teams",
      category: "Payroll",
      price: 399,
      currency: "USD",
      tax_rate: 0,
      unit: "month",
      sku: "PAY-MD-002",
      active: true,
      created_at: daysAgo(60),
    },
    {
      id: uuidv4(),
      name: "QuickBooks Setup & Training",
      description:
        "Complete QuickBooks Online setup, chart of accounts, and 2-hour training session",
      category: "Consulting",
      price: 750,
      currency: "USD",
      tax_rate: 0,
      unit: "one-time",
      sku: "QB-SETUP-001",
      active: true,
      created_at: daysAgo(45),
    },
    {
      id: uuidv4(),
      name: "Financial Statement Preparation",
      description: "Monthly P&L, Balance Sheet, and Cash Flow Statement",
      category: "Reporting",
      price: 450,
      currency: "USD",
      tax_rate: 0,
      unit: "month",
      sku: "RPT-FS-001",
      active: true,
      created_at: daysAgo(45),
    },
    {
      id: uuidv4(),
      name: "Annual Audit Support",
      description: "Documentation preparation and audit assistance",
      category: "Audit",
      price: 3500,
      currency: "USD",
      tax_rate: 0,
      unit: "year",
      sku: "AUD-SUPP-001",
      active: true,
      created_at: daysAgo(30),
    },
  ],
  invoices: [
    {
      id: uuidv4(),
      invoice_number: "INV-2026-001",
      contact_name: "Mike Johnson",
      company_name: "Empire Insulation",
      email: "mike@empireinsulation.com",
      issue_date: "2026-04-01",
      due_date: "2026-04-30",
      status: "paid",
      subtotal: 4500,
      tax: 0,
      discount: 0,
      total: 4500,
      currency: "USD",
      notes: "April bookkeeping + payroll",
      items: JSON.stringify([
        { name: "Monthly Bookkeeping - Medium Business", qty: 1, price: 599 },
        { name: "Payroll Processing - 11-50 employees", qty: 1, price: 399 },
        { name: "Financial Statement Preparation", qty: 1, price: 450 },
      ]),
      responsible: "Govind Kaushik",
      deal_id: "",
      created_at: daysAgo(13),
    },
    {
      id: uuidv4(),
      invoice_number: "INV-2026-002",
      contact_name: "Dr. Anil Gupta",
      company_name: "Gupta Medical Clinic",
      email: "agupta@clinic.com",
      issue_date: "2026-04-05",
      due_date: "2026-05-05",
      status: "sent",
      subtotal: 2500,
      tax: 0,
      discount: 0,
      total: 2500,
      currency: "USD",
      notes: "Fractional CFO - April",
      items: JSON.stringify([{ name: "Fractional CFO Services", qty: 1, price: 2500 }]),
      responsible: "Govind Kaushik",
      deal_id: "",
      created_at: daysAgo(9),
    },
    {
      id: uuidv4(),
      invoice_number: "INV-2026-003",
      contact_name: "David Miller",
      company_name: "Azure Tech LLC",
      email: "david@azuretech.com",
      issue_date: "2026-04-01",
      due_date: "2026-04-15",
      status: "overdue",
      subtotal: 6200,
      tax: 0,
      discount: 0,
      total: 6200,
      currency: "USD",
      notes: "Payroll Q1 2026",
      items: JSON.stringify([
        { name: "Payroll Processing - 11-50 employees", qty: 3, price: 399 },
        { name: "Monthly Bookkeeping - Enterprise", qty: 3, price: 999 },
      ]),
      responsible: "Govind Kaushik",
      deal_id: "",
      created_at: daysAgo(13),
    },
    {
      id: uuidv4(),
      invoice_number: "INV-2026-004",
      contact_name: "Sandeep Sharma",
      company_name: "Sharma Enterprises",
      email: "sandeep@company.com",
      issue_date: "2026-04-10",
      due_date: "2026-05-10",
      status: "draft",
      subtotal: 850,
      tax: 0,
      discount: 0,
      total: 850,
      currency: "USD",
      notes: "Annual tax filing FY2025",
      items: JSON.stringify([
        { name: "Annual Tax Filing - Business (S-Corp)", qty: 1, price: 850 },
      ]),
      responsible: "Govind Kaushik",
      deal_id: "",
      created_at: daysAgo(4),
    },
    {
      id: uuidv4(),
      invoice_number: "INV-2026-005",
      contact_name: "Rajesh Kumar",
      company_name: "TechCorp Solutions",
      email: "rajesh@techcorp.com",
      issue_date: "2026-03-01",
      due_date: "2026-03-30",
      status: "paid",
      subtotal: 1200,
      tax: 0,
      discount: 0,
      total: 1200,
      currency: "USD",
      notes: "QuickBooks setup + March bookkeeping",
      items: JSON.stringify([
        { name: "QuickBooks Setup & Training", qty: 1, price: 750 },
        { name: "Monthly Bookkeeping - Small Business", qty: 1, price: 299 },
      ]),
      responsible: "Govind Kaushik",
      deal_id: "",
      created_at: daysAgo(44),
    },
    {
      id: uuidv4(),
      invoice_number: "INV-2026-006",
      contact_name: "Robert Brown",
      company_name: "Western Holdings",
      email: "r.brown@western.com",
      issue_date: "2026-04-12",
      due_date: "2026-05-12",
      status: "sent",
      subtotal: 3500,
      tax: 0,
      discount: 0,
      total: 3500,
      currency: "USD",
      notes: "Annual Audit Support FY2025",
      items: JSON.stringify([{ name: "Annual Audit Support", qty: 1, price: 3500 }]),
      responsible: "Govind Kaushik",
      deal_id: "",
      created_at: daysAgo(2),
    },
  ],
  quotes: [
    {
      id: uuidv4(),
      quote_number: "QT-2026-001",
      contact_name: "Rajesh Kumar",
      company_name: "TechCorp Solutions",
      email: "rajesh@techcorp.com",
      issue_date: "2026-04-10",
      valid_until: "2026-05-10",
      status: "sent",
      subtotal: 5000,
      tax: 0,
      discount: 500,
      total: 4500,
      currency: "USD",
      notes: "Full-service bookkeeping package — 10% new client discount applied",
      items: JSON.stringify([
        { name: "Monthly Bookkeeping - Medium Business", qty: 12, price: 599 },
      ]),
      responsible: "Govind Kaushik",
      deal_id: "",
      created_at: daysAgo(4),
    },
    {
      id: uuidv4(),
      quote_number: "QT-2026-002",
      contact_name: "Lisa Wang",
      company_name: "ShopRight Inc.",
      email: "lisa@shopright.com",
      issue_date: "2026-04-12",
      valid_until: "2026-04-26",
      status: "draft",
      subtotal: 2800,
      tax: 0,
      discount: 0,
      total: 2800,
      currency: "USD",
      notes: "E-commerce reconciliation and reporting",
      items: JSON.stringify([
        { name: "Monthly Bookkeeping - Small Business", qty: 12, price: 299 },
        { name: "Financial Statement Preparation", qty: 1, price: 450 },
      ]),
      responsible: "Govind Kaushik",
      deal_id: "",
      created_at: daysAgo(2),
    },
    {
      id: uuidv4(),
      quote_number: "QT-2026-003",
      contact_name: "Carlos Hernandez",
      company_name: "Hernandez Tax Services",
      email: "carlos@hernandez.tax",
      issue_date: "2026-03-15",
      valid_until: "2026-03-29",
      status: "expired",
      subtotal: 3000,
      tax: 0,
      discount: 0,
      total: 3000,
      currency: "USD",
      notes: "AP/AR management services",
      items: JSON.stringify([
        { name: "Monthly Bookkeeping - Medium Business", qty: 12, price: 599 },
      ]),
      responsible: "Govind Kaushik",
      deal_id: "",
      created_at: daysAgo(30),
    },
  ],
  hr_departments: [
    { id: "hr-dept-exec",  name: "Executive Leadership",     parent_id: null, head_id: "hr-emp-sunil",     description: "Company leadership and strategic management",     sort_order: 0, created_at: daysAgo(365), updated_at: daysAgo(1) },
    { id: "hr-dept-mkt",   name: "Marketing & Sales",        parent_id: null, head_id: "hr-emp-shubham",   description: "Business development, marketing and sales",         sort_order: 1, created_at: daysAgo(365), updated_at: daysAgo(1) },
    { id: "hr-dept-ops",   name: "Operations",               parent_id: null, head_id: "hr-emp-harvinder", description: "Accounting operations and client delivery",          sort_order: 2, created_at: daysAgo(365), updated_at: daysAgo(1) },
    { id: "hr-dept-it",    name: "IT & Development",         parent_id: null, head_id: "hr-emp-amit",      description: "Technology, web development and IT support",        sort_order: 3, created_at: daysAgo(365), updated_at: daysAgo(1) },
    { id: "hr-dept-admin", name: "Administration & Finance", parent_id: null, head_id: "hr-emp-vinod",     description: "Office administration, HR and finance",             sort_order: 4, created_at: daysAgo(365), updated_at: daysAgo(1) },
  ],
  hr_employees: [
    { id: "hr-emp-sunil",     name: "Sunil Khullar",    position: "Managing Director",                  department_id: "hr-dept-exec",  manager_id: null,              email: "sunil@outsourcedbookeeping.org",     phone: "+91-98765-00001", status: "active", location: "Chandigarh, India", bio: "Managing Director and Administrator. Leads the overall company strategy and operations.",            hire_date: "2010-01-01", created_at: daysAgo(365), updated_at: daysAgo(1) },
    { id: "hr-emp-shubham",   name: "Shubham Khullar",  position: "Business Development Manager",       department_id: "hr-dept-mkt",   manager_id: "hr-emp-sunil",    email: "shubham@outsourcedbookeeping.org",   phone: "+91-98765-00002", status: "active", location: "Chandigarh, India", bio: "Leads business development and marketing. Oversees the marketing & sales team.",                    hire_date: "2014-03-01", created_at: daysAgo(365), updated_at: daysAgo(1) },
    { id: "hr-emp-harvinder", name: "Harvinder Singh",  position: "Deputy Director - Operations",       department_id: "hr-dept-ops",   manager_id: "hr-emp-sunil",    email: "harvinder@outsourcedbookeeping.org", phone: "+91-98765-00003", status: "active", location: "Chandigarh, India", bio: "Oversees all accounting operations and client delivery teams.",                                       hire_date: "2013-06-01", created_at: daysAgo(365), updated_at: daysAgo(1) },
    { id: "hr-emp-vinod",     name: "Vinod Kumar",      position: "Assistant Manager",                  department_id: "hr-dept-admin", manager_id: "hr-emp-sunil",    email: "vinod@outsourcedbookeeping.org",     phone: "+91-98765-00004", status: "active", location: "Chandigarh, India", bio: "Manages administration, IT and finance functions.",                                                   hire_date: "2015-01-01", created_at: daysAgo(365), updated_at: daysAgo(1) },
    { id: "hr-emp-govind",    name: "Govind Kaushik",   position: "Marketing Executive",                department_id: "hr-dept-mkt",   manager_id: "hr-emp-shubham",  email: "govind@outsourcedbookeeping.org",    phone: "+91-98765-00005", status: "active", location: "Chandigarh, India", bio: "Leads marketing campaigns, lead generation and CRM management.",                                     hire_date: "2017-04-01", created_at: daysAgo(365), updated_at: daysAgo(1) },
    { id: "hr-emp-divya",     name: "Divya Verma",      position: "SEO Executive",                      department_id: "hr-dept-mkt",   manager_id: "hr-emp-govind",   email: "divya@outsourcedbookeeping.org",     phone: "+91-98765-00006", status: "active", location: "Chandigarh, India", bio: "Handles SEO optimization and organic traffic growth.",                                                hire_date: "2019-07-01", created_at: daysAgo(365), updated_at: daysAgo(1) },
    { id: "hr-emp-sandeep",   name: "Sandeep Sharma",   position: "Senior SEO Executive",               department_id: "hr-dept-mkt",   manager_id: "hr-emp-govind",   email: "sandeep@outsourcedbookeeping.org",   phone: "+91-98765-00007", status: "active", location: "Chandigarh, India", bio: "Senior SEO specialist managing content strategy and link building.",                                  hire_date: "2018-02-01", created_at: daysAgo(365), updated_at: daysAgo(1) },
    { id: "hr-emp-chaishta",  name: "Chaishta Khullar", position: "Business Development Executive",     department_id: "hr-dept-mkt",   manager_id: "hr-emp-shubham",  email: "chaishta@outsourcedbookeeping.org",  phone: "+91-98765-00008", status: "active", location: "Chandigarh, India", bio: "Focuses on business development and client acquisition.",                                             hire_date: "2020-09-01", created_at: daysAgo(365), updated_at: daysAgo(1) },
    { id: "hr-emp-amrit",     name: "Amrit Kaur",       position: "Marketing Intern",                   department_id: "hr-dept-mkt",   manager_id: "hr-emp-govind",   email: "amrit@outsourcedbookeeping.org",     phone: "+91-98765-00009", status: "active", location: "Chandigarh, India", bio: "Marketing intern assisting with campaigns and social media.",                                         hire_date: "2025-01-01", created_at: daysAgo(365), updated_at: daysAgo(1) },
    { id: "hr-emp-amit",      name: "Amit Kumar",       position: "Web Developer",                      department_id: "hr-dept-it",    manager_id: "hr-emp-shubham",  email: "amit@outsourcedbookeeping.org",      phone: "+91-98765-00010", status: "active", location: "Chandigarh, India", bio: "Full-stack web developer managing company websites and CRM system.",                                  hire_date: "2018-05-01", created_at: daysAgo(365), updated_at: daysAgo(1) },
    { id: "hr-emp-ranjit",    name: "Ranjit Shah",      position: "IT Executive",                       department_id: "hr-dept-it",    manager_id: "hr-emp-vinod",    email: "ranjit@outsourcedbookeeping.org",    phone: "+91-98765-00011", status: "active", location: "Chandigarh, India", bio: "Manages IT infrastructure, hardware and technical support.",                                          hire_date: "2019-03-01", created_at: daysAgo(365), updated_at: daysAgo(1) },
    { id: "hr-emp-harsimran", name: "Harsimran Singh",  position: "Manager - Operations",               department_id: "hr-dept-ops",   manager_id: "hr-emp-harvinder",email: "harsimran@outsourcedbookeeping.org", phone: "+91-98765-00012", status: "active", location: "Chandigarh, India", bio: "Operations manager overseeing all accounting teams and client service delivery.",                     hire_date: "2015-08-01", created_at: daysAgo(365), updated_at: daysAgo(1) },
    { id: "hr-emp-bikker",    name: "Bikker Singh",     position: "Asst Team Leader - Team 4 & 9",      department_id: "hr-dept-ops",   manager_id: "hr-emp-harsimran",email: "bikker@outsourcedbookeeping.org",    phone: "+91-98765-00013", status: "active", location: "Chandigarh, India", bio: "Leads accounting teams 4 and 9 for client bookkeeping.",                                              hire_date: "2016-11-01", created_at: daysAgo(365), updated_at: daysAgo(1) },
    { id: "hr-emp-puneet",    name: "Puneet Kaur",      position: "Asst Team Leader - Team 1 & 2",      department_id: "hr-dept-ops",   manager_id: "hr-emp-harsimran",email: "puneet@outsourcedbookeeping.org",    phone: "+91-98765-00014", status: "active", location: "Chandigarh, India", bio: "Leads accounting teams 1 and 2 for client bookkeeping.",                                              hire_date: "2016-04-01", created_at: daysAgo(365), updated_at: daysAgo(1) },
    { id: "hr-emp-jagdish",   name: "Jagdish Kumar",    position: "Asst Team Leader - Team 7",          department_id: "hr-dept-ops",   manager_id: "hr-emp-harsimran",email: "jagdish@outsourcedbookeeping.org",   phone: "+91-98765-00015", status: "active", location: "Chandigarh, India", bio: "Leads accounting team 7 for client bookkeeping.",                                                     hire_date: "2017-09-01", created_at: daysAgo(365), updated_at: daysAgo(1) },
    { id: "hr-emp-akhilesh",  name: "Akhilesh Pandey",  position: "Senior Accounts - Team 3",           department_id: "hr-dept-ops",   manager_id: "hr-emp-harsimran",email: "akhilesh@outsourcedbookeeping.org",  phone: "+91-98765-00016", status: "active", location: "Chandigarh, India", bio: "Senior accountant in team 3 handling complex client accounts.",                                       hire_date: "2018-01-01", created_at: daysAgo(365), updated_at: daysAgo(1) },
    { id: "hr-emp-gaurav",    name: "Gaurav Kumar",     position: "Senior Accounts - Team 1 & 2",       department_id: "hr-dept-ops",   manager_id: "hr-emp-harsimran",email: "gaurav@outsourcedbookeeping.org",    phone: "+91-98765-00017", status: "active", location: "Chandigarh, India", bio: "Senior accountant supporting teams 1 and 2.",                                                         hire_date: "2017-06-01", created_at: daysAgo(365), updated_at: daysAgo(1) },
    { id: "hr-emp-dhanraj",   name: "Dhanraj Singh",    position: "Office Executive",                   department_id: "hr-dept-admin", manager_id: "hr-emp-vinod",    email: "dhanraj@outsourcedbookeeping.org",   phone: "+91-98765-00018", status: "active", location: "Chandigarh, India", bio: "Manages office operations, supplies and administrative tasks.",                                       hire_date: "2019-10-01", created_at: daysAgo(365), updated_at: daysAgo(1) },
    { id: "hr-emp-dwij",      name: "Dwij Raj Shukla",  position: "Accounts Executive",                 department_id: "hr-dept-admin", manager_id: "hr-emp-vinod",    email: "dwij@outsourcedbookeeping.org",      phone: "+91-98765-00019", status: "active", location: "Chandigarh, India", bio: "Handles company accounts, payroll and financial reporting.",                                          hire_date: "2020-02-01", created_at: daysAgo(365), updated_at: daysAgo(1) },
  ],
};

class JsonDB {
  constructor(filepath) {
    this.filepath = filepath;
    this.data = null;
    this.load();
  }
  load() {
    if (fs.existsSync(this.filepath)) {
      try {
        const existing = JSON.parse(fs.readFileSync(this.filepath, "utf8"));
        // Merge — add new collections if missing
        this.data = existing;
        // Seed any missing collections from defaultData
        Object.keys(defaultData).forEach((k) => {
          if (!this.data[k] || this.data[k].length === 0) this.data[k] = defaultData[k];
        });
        // Ensure new collections exist even if not in defaultData
        [
          "users",
          "tasks",
          "time_logs",
          "task_comments",
          "email_rules",
          "chat_rooms",
          "chat_messages",
          "notifications",
          "scheduled_reports",
          "timeman_records",
          "work_reports",
          "work_schedules",
          "absence_records",
          "system_settings",
          "login_history",
          "user_groups",
          "active_sessions",
          "projects",
          "project_rules",
          "mail_accounts",
          "mail_cache",
          "hr_departments",
          "hr_employees",
          "webhooks",
          "webhook_logs",
          "automation_rules",
          "automation_task_templates",
          "automation_logs",
          "automation_pending",
          "mail_labels",
          "mail_assignment_rules",
          "mail_processed_uids",
          "client_limits",
        ].forEach((k) => {
          if (!this.data[k]) this.data[k] = [];
        });
      } catch {
        this.data = JSON.parse(JSON.stringify(defaultData));
      }
    } else {
      this.data = JSON.parse(JSON.stringify(defaultData));
    }
    // Do NOT call save() here — it would overwrite disk data seeded externally
  }
  save() {
    const json = JSON.stringify(this.data, null, 2);
    const users = (this.data.users||[]).length;
    const tasks = (this.data.tasks||[]).length;
    const mailAccounts = (this.data.mail_accounts||[]).length;
    console.log("[DB SAVE] users=" + users + " tasks=" + tasks + " mail=" + mailAccounts + " len=" + json.length);
    try {
      // Atomic write: write to temp file then rename so a crash never corrupts the DB
      const tmp = this.filepath + ".tmp";
      fs.writeFileSync(tmp, json);
      fs.renameSync(tmp, this.filepath);
    } catch (atomicErr) {
      // Fallback: direct write if atomic write fails (e.g. cross-device rename)
      fs.writeFileSync(this.filepath, json);
    }
  }
  reload() {
    try {
      this.data = JSON.parse(fs.readFileSync(this.filepath, "utf8"));
    } catch {}
  }
  getCollection(name) {
    return this.data[name] || [];
  }
  find(collection, filters = {}) {
    let rows = this.getCollection(collection);
    Object.entries(filters).forEach(([k, v]) => {
      if (v !== undefined && v !== null && v !== "") rows = rows.filter((r) => r[k] === v);
    });
    return rows;
  }
  getById(collection, id) {
    return this.getCollection(collection).find((r) => r.id === id) || null;
  }
  insert(collection, doc) {
    const item = {
      ...doc,
      id: doc.id || uuidv4(),
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    };
    if (!this.data[collection]) this.data[collection] = [];
    this.data[collection].push(item);
    this.save();
    return item;
  }
  update(collection, id, updates) {
    const idx = this.data[collection].findIndex((r) => r.id === id);
    if (idx === -1) return null;
    this.data[collection][idx] = {
      ...this.data[collection][idx],
      ...updates,
      updated_at: new Date().toISOString(),
    };
    this.save();
    return this.data[collection][idx];
  }
  delete(collection, id) {
    const initial = (this.data[collection] || []).length;
    this.data[collection] = (this.data[collection] || []).filter((r) => r.id !== id);
    this.save();
    return initial !== this.data[collection].length;
  }
  deleteMany(collection, ids) {
    this.data[collection] = (this.data[collection] || []).filter((r) => !ids.includes(r.id));
    this.save();
  }
  deleteWhere(collection, filters) {
    this.data[collection] = (this.data[collection] || []).filter(
      (r) => !Object.entries(filters).every(([k, v]) => r[k] === v)
    );
    this.save();
  }
  nextNumber(collection, field, prefix) {
    const rows = this.getCollection(collection);
    if (!rows.length) return `${prefix}-${new Date().getFullYear()}-001`;
    const nums = rows.map((r) => parseInt((r[field] || "").split("-").pop()) || 0);
    const next = Math.max(...nums) + 1;
    return `${prefix}-${new Date().getFullYear()}-${String(next).padStart(3, "0")}`;
  }
}

const db = new JsonDB(DB_PATH);
console.log(
  `✅ CRM Database ready — Leads:${db.getCollection("leads").length} Deals:${
    db.getCollection("deals").length
  } Contacts:${db.getCollection("contacts").length} Products:${
    db.getCollection("products").length
  } Invoices:${db.getCollection("invoices").length}`
);

module.exports = db;